environment:
    type: "NASim"
    name: "SmallGenPO-v0"
n_workers: 8            # Number of environments that are used to sample training data
worker_steps: 512       # Number of steps an agent samples data in each environment (batch size = n_workers * worker_steps)
updates: 250            # 8 * 512 * 250 = 1024000 steps
